1.    apt update
2.    apt upgrade
3.    pkg update && pkg upgrade
4.    pkg install bash
5.    pkg install libwebp
6.    pkg install git
7.    pkg install nodejs
8.    pkg install ffmpeg
9.    pkg install wget
10.  pkg install imagemagick
11.  pkg install yarn
12.  yarn install
13.  npm start
